name: 把网站发布到 Github Pages 上

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-24.04
    steps:
    - name: Sphinx to GitHub Pages
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./source
        requirements_path: ./requirements.txt
        python_version: '3.12'
        cache: true
